site_name: Painkiller (2004) Game Documentation
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Extensions
markdown_extensions:
  - admonition
  - fancyboxmd
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

# Css
extra_css:
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css

# Extra javascript
extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

nav:
  - Home: index.md
  - Painkiller game dev:
    - pk-unpack.md
  - Documentation dev guide:
    - mkdocs-dev.md

repo_url: https://github.com/t3r6/pkdocs